version: "3.3"
services:
  mariadb:
    container_name: mariadb
    build: ./docker/mariadb/
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MARIADB_ROOT_PASSWORD: 'password'
      MARIADB_DATABASE: 'db'
      MARIADB_USER: 'db'
      MARIADB_PASSWORD: 'password'
      MARIADB_AUTO_UPGRADE: 'yes'
    volumes:
      - ./data/db:/var/lib/mysql
  php:
    container_name: php
    build: ./docker/php/
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html
      - ./data/logs:/var/www/logs
  nginx:
    container_name: nginx
    build: ./docker/nginx/
    depends_on:
      - php
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html
      - ./data/logs:/var/www/logs
